#!/bin/bash
# PM Market Intelligence — Setup Wizard
# Run this once to configure the system for your PM profile.
#
# Usage: bash setup.sh

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── Colors ──────────────────────────────────────────────────────────────────
BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
CYAN="\033[0;36m"
RESET="\033[0m"

header()  { echo -e "\n${BOLD}${CYAN}$1${RESET}"; }
success() { echo -e "${GREEN}[OK]${RESET} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET} $1"; }
prompt()  { echo -e -n "${BOLD}$1${RESET} "; }

# ─── Prevent re-running ─────────────────────────────────────────────────────
if [ -f "$REPO_DIR/config.yaml" ]; then
  echo ""
  echo "config.yaml already exists. This setup wizard is for fresh installs."
  echo "Edit config.yaml directly to change settings, or delete it to re-run setup."
  exit 0
fi

echo ""
echo -e "${BOLD}PM Market Intelligence — Setup Wizard${RESET}"
echo "────────────────────────────────────────────────────────────────"
echo "This will take about 5 minutes. Everything stays local."
echo ""

# ─── Step 1: PM Profile ─────────────────────────────────────────────────────
header "Step 1 — Your PM profile"

prompt "Your title (e.g. 'Senior PM', 'Head of Product'):"
read -r PM_NAME

prompt "Your company:"
read -r PM_COMPANY

prompt "Your domain (e.g. 'Developer Platforms', 'B2B SaaS', 'Mobile SDK'):"
read -r PM_DOMAIN

# ─── Step 2: Products ───────────────────────────────────────────────────────
header "Step 2 — Your products"
echo "List your main products. Enter one per line. Press Enter on a blank line when done."
echo ""

OWN_PRODUCTS_YAML=""
PRODUCT_NAMES=()

i=1
while true; do
  prompt "  Product $i name (or Enter to stop):"
  read -r PROD_NAME
  [ -z "$PROD_NAME" ] && break

  prompt "  Product $i short label (e.g. 'CRM', 'API'):"
  read -r PROD_SHORT

  OWN_PRODUCTS_YAML+="    - name: \"$PROD_NAME\"\n"
  OWN_PRODUCTS_YAML+="      short: \"$PROD_SHORT\"\n"
  PRODUCT_NAMES+=("$PROD_SHORT")
  ((i++))
done

# ─── Step 3: Brand monitoring terms ─────────────────────────────────────────
header "Step 3 — Brand monitoring"
echo "Search terms to find mentions of YOUR products on the web."
echo "Include product names, company-specific terms, known aliases."
echo ""

OWN_BRAND_YAML=""
j=1
while true; do
  prompt "  Brand term $j (or Enter to stop):"
  read -r BRAND_TERM
  [ -z "$BRAND_TERM" ] && break
  OWN_BRAND_YAML+="    - \"$BRAND_TERM\"\n"
  ((j++))
done

# ─── Step 4: Competitors ────────────────────────────────────────────────────
header "Step 4 — Competitors"
echo "Primary competitors: direct competitors you track daily."
echo "Extended competitors: broader ecosystem players."
echo ""

PRIMARY_YAML=""
COMPETITOR_LIST=""
echo -e "${BOLD}Primary competitors:${RESET}"
k=1
while true; do
  prompt "  Primary competitor $k (or Enter to stop):"
  read -r COMP
  [ -z "$COMP" ] && break
  PRIMARY_YAML+="    - \"$COMP\"\n"
  [ -n "$COMPETITOR_LIST" ] && COMPETITOR_LIST+=", "
  COMPETITOR_LIST+="$COMP"
  ((k++))
done

EXTENDED_YAML=""
echo ""
echo -e "${BOLD}Extended competitors:${RESET}"
l=1
while true; do
  prompt "  Extended competitor $l (or Enter to stop):"
  read -r COMP
  [ -z "$COMP" ] && break
  EXTENDED_YAML+="    - \"$COMP\"\n"
  [ -n "$COMPETITOR_LIST" ] && COMPETITOR_LIST+=", "
  COMPETITOR_LIST+="$COMP"
  ((l++))
done

# ─── Step 5: Domain & search ────────────────────────────────────────────────
header "Step 5 — Domain and search topics"

prompt "Domain category (e.g. 'B2B SaaS / CRM', 'API tooling / dev infra'):"
read -r DOMAIN_CATEGORY

echo ""
echo "Community subreddits to monitor (e.g. r/programming, r/webdev, r/SaaS)"
echo ""
COMM_SUBS_YAML=""
n=1
while true; do
  prompt "  Subreddit $n (or Enter to stop):"
  read -r SUB
  [ -z "$SUB" ] && break
  COMM_SUBS_YAML+="    - \"$SUB\"\n"
  ((n++))
done

echo ""
echo "Search strings for web sources (used in HN, GitHub, Product Hunt searches)."
echo ""
prompt "Hacker News search (e.g. '\"your topic\" OR \"keyword\"'):"
read -r SEARCH_HN
prompt "GitHub trending search:"
read -r SEARCH_GITHUB
prompt "Product Hunt search:"
read -r SEARCH_PH
prompt "Dev.to/Medium search:"
read -r SEARCH_MEDIUM

# ─── Step 6: Notifications ──────────────────────────────────────────────────
header "Step 6 — Notifications"
echo "How should the pipeline notify you?"
echo "Options: slack | discord | cliq | none"
prompt "Notification type [none]:"
read -r NOTIFY_TYPE
NOTIFY_TYPE="${NOTIFY_TYPE:-none}"

# ─── Step 7: Write config.yaml ──────────────────────────────────────────────
header "Step 7 — Writing config.yaml"

cat > "$REPO_DIR/config.yaml" << EOF
# PM Market Intelligence — Configuration
# Generated by setup.sh — edit freely

pm:
  name: "$PM_NAME"
  company: "$PM_COMPANY"
  domain: "$PM_DOMAIN"

  own_products:
$(echo -e "$OWN_PRODUCTS_YAML")
  own_brand_search_terms:
$(echo -e "$OWN_BRAND_YAML")
competitors:
  primary:
$(echo -e "$PRIMARY_YAML")
  extended:
$(echo -e "$EXTENDED_YAML")
domain:
  category: "$DOMAIN_CATEGORY"

  community_subreddits:
$(echo -e "$COMM_SUBS_YAML")
  search_queries:
    hn: '$SEARCH_HN'
    github: '$SEARCH_GITHUB'
    producthunt: '$SEARCH_PH'
    medium_devto: '$SEARCH_MEDIUM'

notifications:
  type: "$NOTIFY_TYPE"
EOF

success "Created: config.yaml"

# ─── Step 8: Create .env ────────────────────────────────────────────────────
header "Step 8 — Setting up .env"

if [ -f "$REPO_DIR/.env" ]; then
  warn ".env already exists — skipping. Edit it manually if needed."
else
  echo ""
  echo "API keys — press Enter to skip any you don't have yet."
  echo ""
  prompt "xAI API key (optional, for X/Twitter intelligence):"
  read -rs XAI_KEY; echo ""

  NOTIFY_VARS=""
  if [ "$NOTIFY_TYPE" = "slack" ]; then
    prompt "Slack webhook URL:"
    read -rs SLACK_URL; echo ""
    NOTIFY_VARS="SLACK_WEBHOOK_URL=\"$SLACK_URL\""
  elif [ "$NOTIFY_TYPE" = "discord" ]; then
    prompt "Discord webhook URL:"
    read -rs DISCORD_URL; echo ""
    NOTIFY_VARS="DISCORD_WEBHOOK_URL=\"$DISCORD_URL\""
  elif [ "$NOTIFY_TYPE" = "cliq" ]; then
    prompt "Cliq bot incoming URL:"
    read -rs CLIQ_URL; echo ""
    prompt "Cliq bot token:"
    read -rs CLIQ_TOKEN; echo ""
    NOTIFY_VARS="CLIQ_BOT_INCOMING_URL=\"$CLIQ_URL\"\nCLIQ_BOT_TOKEN=\"$CLIQ_TOKEN\""
  fi

  cat > "$REPO_DIR/.env" << ENVEOF
# PM Market Intel — Secrets (never commit this file)
XAI_API_KEY="$XAI_KEY"
$(echo -e "$NOTIFY_VARS")
ENVEOF

  chmod 600 "$REPO_DIR/.env"
  success "Created: .env"
fi

# ─── Step 9: Create directories ─────────────────────────────────────────────
header "Step 9 — Creating directories"

mkdir -p \
  "$REPO_DIR/context/products" \
  "$REPO_DIR/outputs/signals" \
  "$REPO_DIR/outputs/briefs" \
  "$REPO_DIR/logs"

success "Directory structure created"

# ─── Step 10: Generate CLAUDE.md ─────────────────────────────────────────────
header "Step 10 — Generating CLAUDE.md"

PRODUCT_LIST=""
for p in "${PRODUCT_NAMES[@]}"; do
  [ -n "$PRODUCT_LIST" ] && PRODUCT_LIST+=", "
  PRODUCT_LIST+="$p"
done

cat > "$REPO_DIR/CLAUDE.md" << CLAUDEEOF
# PM Market Intelligence — Project Context

## Who This Is For

**Role:** $PM_NAME at $PM_COMPANY
**Domain:** $PM_DOMAIN
**Products:** $PRODUCT_LIST

## What This System Does

This is a daily market intelligence pipeline. It gathers signals from developer communities and the open web, validates them against your product context, and delivers a prioritized strategic brief.

## Products

$(echo -e "$OWN_PRODUCTS_YAML" | sed 's/^    - name: /- /; s/^      short: /  Short: /')

## Competitors

Known competitors (anything NOT on this list = potential new entrant):
$COMPETITOR_LIST

## Operating Rules

- Lead with the signal and its implication, not background context
- Every signal must have a source URL
- Separate confirmed facts from inferences — label which is which
- Connect every signal to a specific product — not the company generically
- If evidence is weak, say so explicitly
- No generic industry commentary — everything must be relevant to these products
CLAUDEEOF

success "Created: CLAUDE.md"

# ─── Done ────────────────────────────────────────────────────────────────────
echo ""
echo "────────────────────────────────────────────────────────────────"
echo -e "${BOLD}${GREEN}Setup complete!${RESET}"
echo ""
echo "What's ready:"
echo "  - config.yaml     — your settings"
echo "  - .env            — your secrets (gitignored)"
echo "  - CLAUDE.md       — your project context"
echo ""
echo "Next steps:"
echo ""
echo "  1. ${BOLD}Add product context${RESET} (recommended)"
echo "     Create one .md file per product in context/products/"
echo "     Include: what it does, target users, current stage, open decisions"
echo ""
echo "  2. ${BOLD}Run your first scan${RESET}"
echo "     bash run.sh"
echo ""
echo "  3. ${BOLD}Schedule it daily${RESET} (optional)"
echo "     crontab -e"
echo "     Add: 0 7 * * * cd $(pwd) && bash run.sh >> logs/cron.log 2>&1"
echo ""